server:
  port: 5555

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mailservice
    username: pawan
    password: pawan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: pawankarri55@gmail.com
    password: fxwnacokcnahlbme
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB




files:
  storage: C:/eidikoportal/templates

logging:
  file:
    name: "C:/logs/eidiko-mail-service.log"
  logback:
    rollingpolicy:
      file-name-pattern: C:/logs/eidiko-mail-service-%d{yyyy-MM-dd}.%i.log

